export const Advantage = [
  {
    id: 1,
    name: "Never cook again!",
    info: "Going on vacation? Just pause your subscription, and we refund unused days.",
    infinite: true,
    apple: false,
    leaf: false,
    pause: false,
  },
  {
    id: 2,
    css: { background: "#FDF2E9" },
    name: "Local and organic",
    info: "Our subscriptions cover 365 days per year, even including major holidays",
    infinite: false,
    apple: true,
    leaf: false,
    pause: false,
  },
  {
    id: 3,
    name: "No waste",
    price: 399,
    info: "Our cooks only use local, fresh, and organic products to prepare your meals.",
    infinite: false,
    apple: false,
    leaf: true,
    pause: false,
  },
  {
    id: 2,
    name: "Pause anytime",
    info: "Going on vacation? Just pause your subscription, and we refund unused days.",
    infinite: false,
    apple: false,
    leaf: false,
    pause: true,
  },
];
